apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-tool
  namespace: artem
  labels:
    app: sre-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-tool
  template:
    metadata:
      labels:
        app: sre-tool
    spec:
      priorityClassName: artem-buggy-pod-high-priority
      containers:
      - name: sre
        image: docker pull ghcr.io/imroot2202/sre-tool-example:main #ghcr.io/imroot2202/sre-cli:0.0.4
        command: ["/bin/sh"]
        args: ["-c", "echo 'Please run your command here' && sleep infinity"]
