apiVersion: v1
kind: Pod
metadata:
  annotations:
    labels:
    app: nginx
  name: healthy-pod
  namespace: artem
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources: 
      limits:
        memory: "10Gi"
      requests:
        memory: "50Mi"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-saas-sre-interview-primary-nodes-df793e8b-7s58
  preemptionPolicy: PreemptLowerPriority
